# THIS FILE IS AUTO-GENERATED — DO NOT EDIT BY HAND.
# Source: packages/contracts/schemas/*.schema.json
# Regenerate: pnpm -C packages/contracts run generate
# generated by datamodel-codegen:
#   filename:  agent-sse-event.schema.json

from __future__ import annotations

from enum import Enum
from typing import Any, Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, RootModel


class TokenEvent(BaseModel):
    """
    LLM 토큰 스트리밍 조각. 영속화되지 않으며 최종 message 이벤트만 저장된다.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["1.0.0"]
    type: Literal["token"]
    seq: int = Field(..., ge=0)
    """
    런 내 단조 증가 시퀀스.
    """
    delta: str
    """
    assistant 응답의 토큰 조각. 누적은 클라이언트가 한다.
    """


class ToolKind(Enum):
    """
    도구 분류 (chat_tool_calls.tool_kind 와 정합).
    """

    retrieval = "retrieval"
    db_query = "db_query"
    external_api = "external_api"
    ai_model = "ai_model"
    rule_engine = "rule_engine"
    render = "render"
    notification = "notification"
    other = "other"


class Status(Enum):
    """
    도구 라이프사이클 상태.
    """

    started = "started"
    succeeded = "succeeded"
    failed = "failed"


class ToolStepEvent(BaseModel):
    """
    도구 호출 진행 상황. 원장(chat_tool_calls) 의 사용자 친화 투영.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["1.0.0"]
    type: Literal["tool_step"]
    seq: int = Field(..., ge=0)
    tool_name: str = Field(..., min_length=1)
    """
    실행 중/완료된 도구 이름.
    """
    tool_kind: ToolKind
    """
    도구 분류 (chat_tool_calls.tool_kind 와 정합).
    """
    status: Status
    """
    도구 라이프사이클 상태.
    """
    summary: str | None = None
    """
    사용자 노출용 짧은 진행 요약.
    """
    error_code: str | None = None
    """
    status=failed 시 안정적 에러 코드.
    """


class SessionStatus(Enum):
    """
    세션 상태 머신의 새 상태.
    """

    draft = "draft"
    address_ready = "address_ready"
    floorplan_selected = "floorplan_selected"
    analyzing = "analyzing"
    awaiting_overlay = "awaiting_overlay"
    collecting_info = "collecting_info"
    ready_for_rule = "ready_for_rule"
    report_ready = "report_ready"
    handoff = "handoff"
    expired = "expired"
    deleted = "deleted"


class CompletionDecision(Enum):
    """
    FLOW_GUARD 결정 (completion-decision 계약의 decision enum 재사용).
    """

    ASK_MORE = "ASK_MORE"
    REQUEST_OVERLAY_REVIEW = "REQUEST_OVERLAY_REVIEW"
    PROCEED_RULE = "PROCEED_RULE"
    HOLD_OR_HANDOFF = "HOLD_OR_HANDOFF"
    NoneType_None = None


class StateChangeEvent(BaseModel):
    """
    세션 status / completion_decision 전이 알림.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["1.0.0"]
    type: Literal["state_change"]
    seq: int = Field(..., ge=0)
    session_status: SessionStatus
    """
    세션 상태 머신의 새 상태.
    """
    completion_decision: CompletionDecision | None = None
    """
    FLOW_GUARD 결정 (completion-decision 계약의 decision enum 재사용).
    """


class Role(Enum):
    """
    런타임이 만든 메시지 role.
    """

    assistant = "assistant"
    system = "system"
    tool = "tool"


class MessageEvent(BaseModel):
    """
    완료된 메시지 (영속화 후 전송).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["1.0.0"]
    type: Literal["message"]
    seq: int = Field(..., ge=0)
    role: Role
    """
    런타임이 만든 메시지 role.
    """
    content: str
    """
    완료된 메시지 본문.
    """
    message_id: UUID | None = None
    """
    영속화된 chat_messages.id.
    """
    ui_components: list[dict[str, Any]] | None = None
    """
    A2UI 렌더링 payload (chat_messages.ui_components 와 정합).
    """


class ErrorEvent(BaseModel):
    """
    런 중 발생한 오류.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["1.0.0"]
    type: Literal["error"]
    seq: int = Field(..., ge=0)
    error_code: str
    """
    안정적 에러 코드.
    """
    message: str
    """
    사람이 읽을 수 있는 짧은 메시지.
    """
    recoverable: bool
    """
    true 면 스트림이 계속될 수 있고, false 면 done 이 뒤따른다.
    """


class RunStatus(Enum):
    """
    런 종료 상태. awaiting_input/interrupted 는 resume 가능.
    """

    succeeded = "succeeded"
    failed = "failed"
    awaiting_input = "awaiting_input"
    interrupted = "interrupted"
    cancelled = "cancelled"


class DoneEvent(BaseModel):
    """
    스트림 종료 신호. 항상 마지막 이벤트.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["1.0.0"]
    type: Literal["done"]
    seq: int = Field(..., ge=0)
    run_status: RunStatus
    """
    런 종료 상태. awaiting_input/interrupted 는 resume 가능.
    """


class AgentSseEvent(
    RootModel[
        TokenEvent
        | ToolStepEvent
        | StateChangeEvent
        | MessageEvent
        | ErrorEvent
        | DoneEvent
    ]
):
    root: (
        TokenEvent
        | ToolStepEvent
        | StateChangeEvent
        | MessageEvent
        | ErrorEvent
        | DoneEvent
    ) = Field(..., title="AgentSseEvent")
    """
    에이전트 런 SSE 스트림의 단일 이벤트 envelope. SSE `event:` 필드가 type, `data:` 필드가 본 JSON 이다. type 별 discriminated union — 클라이언트는 type 으로 분기한다.
    """
