# THIS FILE IS AUTO-GENERATED — DO NOT EDIT BY HAND.
# Source: packages/contracts/schemas/*.schema.json
# Regenerate: pnpm -C packages/contracts run generate
# generated by datamodel-codegen:
#   filename:  agent-run-status.schema.json

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field


class Status(Enum):
    """
    런 상태 머신.
    """

    pending = "pending"
    running = "running"
    awaiting_input = "awaiting_input"
    interrupted = "interrupted"
    succeeded = "succeeded"
    failed = "failed"
    cancelled = "cancelled"


class AgentRunStatus(BaseModel):
    """
    agent_runs row 의 클라이언트 노출 투영. `GET /sessions/{session_id}/agent/runs/{run_id}` 정본. 재연결 시 재스트림 없이 상태를 확인하는 데 쓴다.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["1.0.0"] = Field(..., pattern="^\\d+\\.\\d+\\.\\d+$")
    """
    스키마 버전 (semver).
    """
    id: UUID
    """
    agent_runs.id.
    """
    session_id: UUID
    """
    소유 세션 id.
    """
    thread_id: UUID
    """
    LangGraph 체크포인터 thread_id (= session_id).
    """
    status: Status
    """
    런 상태 머신.
    """
    model: str
    """
    이 런에 사용된 LLM 모델 식별자 (예: openai:gpt-5.4-mini).
    """
    current_step: str | None = None
    """
    마지막으로 진입한 플로우 단계 라벨.
    """
    langsmith_run_url: str | None = None
    """
    LangSmith 트레이스 URL (있으면).
    """
    error_code: str | None = None
    """
    실패 시 안정적 에러 코드.
    """
    error_message: str | None = None
    """
    실패 시 사람이 읽을 수 있는 짧은 메시지 (원본 payload·PII 비포함).
    """
    started_at: datetime | None = None
    """
    런 시작 시각.
    """
    finished_at: datetime | None = None
    """
    런 종료 시각.
    """
    created_at: datetime
    """
    row 생성 시각.
    """
