# THIS FILE IS AUTO-GENERATED — DO NOT EDIT BY HAND.
# Source: packages/contracts/schemas/*.schema.json
# Regenerate: pnpm -C packages/contracts run generate
# generated by datamodel-codegen:
#   filename:  agent-run-request.schema.json

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field


class UserMessage(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    role: Literal["user"]
    """
    공개 endpoint 에서 클라이언트가 만들 수 있는 유일한 role.
    """
    content: str = Field(..., min_length=1)
    """
    사용자 발화 본문.
    """


class AgentRunRequest(BaseModel):
    """
    에이전트 세션 런 시작 요청 body. `POST /sessions/{session_id}/agent/runs` 정본. 클라이언트는 role='user' message 만 보낼 수 있고, assistant/tool message 는 런타임만 생성한다.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["1.0.0"] = Field(..., pattern="^\\d+\\.\\d+\\.\\d+$")
    """
    스키마 버전 (semver). 본 시점 고정값.
    """
    message: UserMessage
    """
    이번 턴의 사용자 입력 메시지.
    """
    metadata: dict[str, Any] | None = None
    """
    런타임/관측용 부가 정보. 신뢰할 수 없는 입력이므로 service-controlled 필드로 승격하지 않는다.
    """
