# THIS FILE IS AUTO-GENERATED — DO NOT EDIT BY HAND.
# Source: packages/contracts/schemas/*.schema.json
# Regenerate: pnpm -C packages/contracts run generate
# generated by datamodel-codegen:
#   filename:  common-judgment-schema.schema.json

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Literal
from uuid import UUID

from pydantic import BaseModel, ConfigDict, Field, RootModel


class SelectedWall(RootModel[str]):
    root: str = Field(..., min_length=1)


class BuildingType(Enum):
    """
    건물 유형.
    """

    APARTMENT = "APARTMENT"
    OFFICETEL = "OFFICETEL"
    ROW_HOUSE = "ROW_HOUSE"
    MULTI_FAMILY = "MULTI_FAMILY"
    ETC = "ETC"


class BuildingInfo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    address_normalized: str = Field(..., min_length=1)
    """
    도로명주소 API 가 정규화한 주소 문자열.
    """
    dong: str | None = None
    """
    동 식별자.
    """
    ho: str | None = None
    """
    호 식별자.
    """
    floor: int | None = None
    """
    층수. 룰 평가의 1차 입력.
    """
    total_floors: int | None = Field(None, ge=1)
    """
    건물 전체 층수.
    """
    building_type: BuildingType
    """
    건물 유형.
    """
    approx_built_year: int | None = Field(None, ge=1900, le=2100)
    """
    추정 준공년도.
    """


class MaskCoord(BaseModel):
    """
    도면 좌표계 위 한 점 (px or normalized).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    x: float
    y: float


class Type(Enum):
    """
    정규화된 공간 타입.
    """

    LIVING_ROOM = "LIVING_ROOM"
    KITCHEN = "KITCHEN"
    BEDROOM = "BEDROOM"
    BATHROOM = "BATHROOM"
    BALCONY = "BALCONY"
    EVACUATION_SPACE = "EVACUATION_SPACE"
    STAIRWELL = "STAIRWELL"
    CORRIDOR = "CORRIDOR"
    ETC = "ETC"


class SourceEngine(Enum):
    """
    이 객체를 생성한 엔진.
    """

    MASK2FORMER = "MASK2FORMER"
    SAM2 = "SAM2"
    VLM = "VLM"
    HITL = "HITL"


class SpaceObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(..., min_length=1)
    label: str
    """
    사람이 읽는 라벨 (예: '거실', '주방', '대피공간').
    """
    type: Type
    """
    정규화된 공간 타입.
    """
    mask_coords: list[MaskCoord] = Field(..., min_length=3)
    """
    공간 폴리곤 좌표.
    """
    confidence: float = Field(..., ge=0.0, le=1.0)
    """
    세그멘테이션 신뢰도.
    """
    source_engine: SourceEngine
    """
    이 객체를 생성한 엔진.
    """


class WallType(Enum):
    """
    벽체 종류. UNKNOWN 은 보완 루프 트리거.
    """

    NON_LOAD_BEARING = "NON_LOAD_BEARING"
    LOAD_BEARING = "LOAD_BEARING"
    UNKNOWN = "UNKNOWN"


class SourceEngine1(Enum):
    MASK2FORMER = "MASK2FORMER"
    SAM2 = "SAM2"
    VLM = "VLM"
    HITL = "HITL"


class WallObject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str = Field(..., min_length=1)
    wall_type: WallType
    """
    벽체 종류. UNKNOWN 은 보완 루프 트리거.
    """
    confidence: float = Field(..., ge=0.0, le=1.0)
    coords: list[MaskCoord] = Field(..., min_length=2)
    """
    벽체 선분/폴리라인 좌표.
    """
    source_engine: SourceEngine1


class Provider(Enum):
    """
    VLM 프로바이더 (ADR-0001 §7 의 VLMClient 인터페이스 호환).
    """

    OPENAI = "OPENAI"
    ANTHROPIC = "ANTHROPIC"
    GOOGLE = "GOOGLE"
    OTHER = "OTHER"


class Reclassification(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    object_id: str = Field(..., min_length=1)
    new_label: str = Field(..., min_length=1)
    reason: str


class VlmSupplement(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    provider: Provider | None = None
    """
    VLM 프로바이더 (ADR-0001 §7 의 VLMClient 인터페이스 호환).
    """
    model: str | None = None
    """
    예: 'gpt-5.4-mini', 'gpt-5.5'.
    """
    notes: list[str] | None = None
    """
    VLM 자유 텍스트 주석.
    """
    reclassifications: list[Reclassification] | None = None
    """
    Mask2Former 라벨을 VLM 이 교정한 결과.
    """


class WindowForm(Enum):
    """
    창호 형태.
    """

    FIXED = "FIXED"
    OPENABLE = "OPENABLE"
    FOLDING = "FOLDING"
    SLIDING = "SLIDING"
    OTHER = "OTHER"
    NoneType_None = None


class JudgmentValues(BaseModel):
    """
    CHAT 이 사용자로부터 수집한 RULE 입력 변수 모음. SDD §5.2.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    floor_count: int | None = Field(None, ge=1)
    """
    건물 층수.
    """
    has_sprinkler: bool | None = None
    """
    스프링클러 설치 여부.
    """
    has_evacuation_space: bool | None = None
    """
    대피공간 존재 여부.
    """
    stairwell_count: int | None = Field(None, ge=0)
    """
    계단실 수.
    """
    window_form: WindowForm | None = None
    """
    창호 형태.
    """
    balcony_attached: bool | None = None
    """
    발코니 접합 여부.
    """
    permit_history_known: bool | None = None
    """
    기존 행위허가 이력 존재 여부.
    """


class CommonJudgmentSchema(BaseModel):
    """
    공통 판단 스키마 — AI 분석·OVERLAY 선택·CHAT 보완값이 CHAT/session 에서 병합되어 FLOW_GUARD 평가를 거쳐 RULE 의 단일 입력 컨트랙트가 된다. SDD §5.2 정본.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    session_id: UUID
    """
    세션 추적 식별자.
    """
    analyzed_at: datetime
    """
    AI 분석 시점 (ISO-8601).
    """
    schema_version: Literal["1.0.0"] = Field(..., pattern="^\\d+\\.\\d+\\.\\d+$")
    """
    스키마 버전 (semver). 본 ADR-0001 / CMP-527 시점 고정값.
    """
    building_info: BuildingInfo
    space_objects: list[SpaceObject]
    """
    공간 객체 목록.
    """
    wall_objects: list[WallObject]
    """
    벽체 객체 목록.
    """
    vlm_supplement: VlmSupplement | None = None
    """
    VLM 재분류·주석 결과. 분석이 보류된 경우 null 또는 부재.
    """
    selected_walls: list[SelectedWall]
    """
    OVERLAY 가 수집한 사용자 선택 철거 대상 벽체 region_id 목록. 기능명세서 §2.5 의 target_wall(단수)를 대체한다 — 복수 벽 동시 선택을 지원하는 정본.
    """
    target_space: str | None = None
    """
    사용자가 지정한 변경 희망 공간 region_id. 미지정 시 null.
    """
    judgment_values: JudgmentValues
    rule_input_ready: bool
    """
    RULE 진입 가능 여부. false면 CHAT/FLOW_GUARD 가 추가 정보를 수집한다.
    """
