# THIS FILE IS AUTO-GENERATED — DO NOT EDIT BY HAND.
# Source: packages/contracts/schemas/*.schema.json
# Regenerate: pnpm -C packages/contracts run generate
# generated by datamodel-codegen:
#   filename:  completion-decision.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel


class Decision(Enum):
    """
    결정 분기. SDD §4.7 의 4가지: ASK_MORE(추가 질의), REQUEST_OVERLAY_REVIEW(도면 재확인), PROCEED_RULE(룰 평가 진행), HOLD_OR_HANDOFF(보류·상담 전환).
    """

    ASK_MORE = "ASK_MORE"
    REQUEST_OVERLAY_REVIEW = "REQUEST_OVERLAY_REVIEW"
    PROCEED_RULE = "PROCEED_RULE"
    HOLD_OR_HANDOFF = "HOLD_OR_HANDOFF"


class MissingField(RootModel[str]):
    root: str = Field(..., min_length=1)


class ConfidenceSummary(BaseModel):
    """
    신뢰도 요약. flow_guard_decisions 영속화에 사용 (SDD §6.3).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    ai_overall: float | None = Field(None, ge=0.0, le=1.0)
    """
    AI 분석 종합 신뢰도.
    """
    overlay_overall: float | None = Field(None, ge=0.0, le=1.0)
    """
    OVERLAY 선택값 종합 신뢰도.
    """


class ConflictFlag(Enum):
    WALL_TYPE_CONFLICT = "WALL_TYPE_CONFLICT"
    OVERLAY_SELECTION_OUT_OF_SCOPE = "OVERLAY_SELECTION_OUT_OF_SCOPE"
    LOAD_BEARING_SELECTED = "LOAD_BEARING_SELECTED"
    EVACUATION_SPACE_REMOVAL = "EVACUATION_SPACE_REMOVAL"
    AI_LOW_CONFIDENCE = "AI_LOW_CONFIDENCE"
    USER_CONTRADICTION = "USER_CONTRADICTION"


class Kind(Enum):
    """
    행동 종류.
    """

    ASK_USER_QUESTION = "ASK_USER_QUESTION"
    RE_OPEN_OVERLAY = "RE_OPEN_OVERLAY"
    INVOKE_RULE = "INVOKE_RULE"
    OFFER_HANDOFF = "OFFER_HANDOFF"


class Channel(Enum):
    """
    행동을 노출할 채널.
    """

    INLINE_CHAT = "INLINE_CHAT"
    OVERLAY_PANEL = "OVERLAY_PANEL"
    HANDOFF_CTA = "HANDOFF_CTA"
    NoneType_None = None


class NextAction(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Kind
    """
    행동 종류.
    """
    target_field: str | None = None
    """
    ASK_USER_QUESTION 인 경우 보완 대상 필드 경로.
    """
    prompt: str | None = None
    """
    사용자에게 노출되는 보완 질의 문구 (생활어, NFR-QUAL 의 비전문 사용자 친화 원칙).
    """
    channel: Channel | None = None
    """
    행동을 노출할 채널.
    """


class CompletionDecision(BaseModel):
    """
    FLOW_GUARD 의 충분성·충돌·고위험 판정 결과. CHAT/OVERLAY/RULE 분기를 결정한다. SDD §4.7·§5.1 (I-FLOW-02) 정본.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["1.0.0"] = Field(..., pattern="^\\d+\\.\\d+\\.\\d+$")
    """
    스키마 버전 (semver). 본 ADR-0001 / CMP-527 시점 고정값.
    """
    decision: Decision
    """
    결정 분기. SDD §4.7 의 4가지: ASK_MORE(추가 질의), REQUEST_OVERLAY_REVIEW(도면 재확인), PROCEED_RULE(룰 평가 진행), HOLD_OR_HANDOFF(보류·상담 전환).
    """
    reason: str = Field(..., min_length=1)
    """
    결정 사유. 사용자 노출 텍스트가 아닌 디버그/감사용. 결정성 보장을 위해 한 줄.
    """
    missing_fields: list[MissingField]
    """
    보완이 필요한 CommonJudgmentSchema 필드 경로 목록 (예: 'judgment_values.has_sprinkler').
    """
    next_actions: list[NextAction]
    """
    후속 행동 시퀀스. 클라이언트/CHAT 가 그대로 dispatch 한다.
    """
    confidence_summary: ConfidenceSummary | None = None
    """
    신뢰도 요약. flow_guard_decisions 영속화에 사용 (SDD §6.3).
    """
    conflict_flags: list[ConflictFlag] | None = None
    """
    감지된 충돌 종류. 동시에 다수 발생하면 HOLD_OR_HANDOFF 로 보수 분기 (DECISION_AMBIGUOUS, SDD §4.7).
    """
