# THIS FILE IS AUTO-GENERATED — DO NOT EDIT BY HAND.
# Source: packages/contracts/schemas/*.schema.json
# Regenerate: pnpm -C packages/contracts run generate
# generated by datamodel-codegen:
#   filename:  error-response.schema.json

from __future__ import annotations

from datetime import datetime
from typing import Any

from pydantic import BaseModel, ConfigDict, Field


class ErrorBody(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: str = Field(
        ...,
        examples=[
            "INSUFFICIENT_DATA",
            "SEGMENTATION_FAILED",
            "VLM_TIMEOUT",
            "ANALYSIS_LOW_CONFIDENCE",
            "RULE_EXCEPTION",
            "DECISION_AMBIGUOUS",
            "AGENT_TIMEOUT",
            "LOOP_OVERFLOW",
            "REPORT_GENERATION_FAILED",
            "LEAD_NOTIFY_FAILED",
            "PRICING_POLICY_MISSING",
            "ESTIMATE_OUT_OF_RANGE",
        ],
        min_length=1,
    )
    """
    도메인 에러 코드. SDD §8.2 가 AI 단계 코드를 정의 (SEGMENTATION_FAILED / VLM_TIMEOUT / ANALYSIS_LOW_CONFIDENCE 등). 추가 코드는 모듈별 README 에 등재한다.
    """
    message: str = Field(..., min_length=1)
    """
    사용자/디버그용 메시지. PII 미포함.
    """
    request_id: str = Field(..., min_length=1)
    """
    structlog request_id 컨텍스트와 일치 (AGENTS.md §4.5).
    """
    timestamp: datetime
    """
    에러 발생 시각 (ISO-8601, UTC).
    """
    details: dict[str, Any] | None = None
    """
    도메인별 추가 컨텍스트 (예: missing_fields, retry_after). 스키마 미고정.
    """


class ErrorResponse(BaseModel):
    """
    표준 에러 응답 포맷. 모든 백엔드 모듈은 AGENTS.md §4.5 에 따라 본 포맷으로 응답한다. ZippinException 계열이 공통 핸들러를 거쳐 본 형태로 직렬화된다.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    error: ErrorBody
