# THIS FILE IS AUTO-GENERATED — DO NOT EDIT BY HAND.
# Source: packages/contracts/schemas/*.schema.json
# Regenerate: pnpm -C packages/contracts run generate
# generated by datamodel-codegen:
#   filename:  home-check.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field


class Status(Enum):
    """
    잡 상태. needs_input = 동·호 자동매칭 실패 또는 보안문자(reqSecureNo) 발생 폴백.
    """

    pending = "pending"
    querying = "querying"
    needs_input = "needs_input"
    completed = "completed"
    failed = "failed"


class Signal(Enum):
    """
    종합 신호등. status=completed 일 때만 채워진다. violation=🔴, caution=🟡, normal=🟢.
    """

    violation = "violation"
    caution = "caution"
    normal = "normal"
    NoneType_None = None


class ErrorInfo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    code: str
    """
    오류 코드 (예: UPSTREAM_UNAVAILABLE, NOT_FOUND, INVALID_ADDRESS).
    """
    message: str
    """
    사용자 안내용 메시지.
    """


class Kind(Enum):
    """
    폴백 종류. dong_ho=주소·동·호 후보 선택 필요, secure_no=보안문자 입력 필요.
    """

    dong_ho = "dong_ho"
    secure_no = "secure_no"


class FieldModel(Enum):
    """
    kind=dong_ho 일 때 사용자가 골라야 하는 축(address=주소, dong=동, ho=호). options 와 함께 채워진다.
    """

    address = "address"
    dong = "dong"
    ho = "ho"
    NoneType_None = None


class NeedsInputOption(BaseModel):
    """
    동·호·주소 선택 후보 1건.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    value: str
    """
    재개(continue) 시 selection 으로 그대로 전송할 CODEF 식별자(호=commHoNum, 동=commDongNum, 주소=지번/도로명).
    """
    label: str
    """
    사용자 표시용 명칭(호=reqHo, 동=reqDong, 주소=도로명/지번).
    """
    area: str | None = None
    """
    전유면적(㎡, reqArea). 호 후보에만 제공 — 같은 번호의 호를 면적으로 구분하는 데 쓴다.
    """


class Signal1(Enum):
    """
    종합 신호등.
    """

    violation = "violation"
    caution = "caution"
    normal = "normal"


class ExtensionVerdict(Enum):
    """
    신고 확장 ↔ 변동사항 대조 판정값. (패키지 루트 export 충돌 방지를 위해 rule-eval 의 Verdict 와 다른 이름을 쓴다.)
    """

    violation = "violation"
    legal = "legal"
    uncertain = "uncertain"


class ExtensionCheck(BaseModel):
    """
    신고 확장 ↔ 대장 변동사항 대조(LLM). 노란딱지(violation.is_violation)와 별개 축. verdict=violation 이면 종합 signal 을 violation 으로 올리되 violation.is_violation(공식 표시)은 건드리지 않는다.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    verdict: ExtensionVerdict
    """
    violation=신고했으나 미등재, legal=등재확인/확장없음, uncertain=대조모호.
    """
    reason: str | None = None
    """
    한국어 판정 근거(대장 변동사항 기준).
    """
    reported_areas: list[str] | None = None
    """
    사용자가 신고한 확장 부위.
    """
    matched_areas: list[str] | None = None
    """
    변동사항에서 등재 확인된 부위.
    """
    unrecorded_areas: list[str] | None = None
    """
    신고했으나 미등재된 부위(위반 소지).
    """


class Violation(BaseModel):
    """
    노란딱지(위반건축물) 판정. is_violation = 전유부 OR 표제부 resViolationStatus=='위반건축물'.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    is_violation: bool
    """
    종합 위반 여부.
    """
    exclusive: bool | None = None
    """
    전유부 위반표시.
    """
    heading: bool | None = None
    """
    표제부(건물) 위반표시.
    """
    raw: str | None = None
    """
    원본 resViolationStatus 값(예: '위반건축물').
    """


class AddressInfo(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    road_addr: str | None = None
    """
    도로명주소.
    """
    jibun_addr: str | None = None
    """
    지번주소.
    """
    dong: str | None = None
    """
    동.
    """
    ho: str | None = None
    """
    호.
    """


class ExclusivePart(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    area_m2: float | None = None
    """
    전유면적(㎡).
    """
    use_type: str | None = None
    """
    용도(resUseType).
    """
    structure: str | None = None
    """
    구조(resStructure).
    """
    floor: str | None = None
    """
    층(resFloor).
    """


class BuildingHeading(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    main_use: str | None = None
    """
    주용도.
    """
    floors: str | None = None
    """
    층수(예: '지하 1층 지상 12층').
    """
    approval_date: str | None = None
    """
    사용승인일.
    """
    permit_date: str | None = None
    """
    허가일.
    """
    comm_unique_no: str | None = None
    """
    표제부 고유번호.
    """


class Source(Enum):
    """
    출처 대장(전유부/표제부).
    """

    exclusive = "exclusive"
    heading = "heading"


class ChangeEntry(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date: str | None = None
    """
    변동일자(정규화 문자열).
    """
    reason: str
    """
    변동내용 및 원인(resChangeReason).
    """
    source: Source
    """
    출처 대장(전유부/표제부).
    """


class Kind1(Enum):
    """
    PDF 종류.
    """

    exclusive_part = "exclusive_part"
    building_heading = "building_heading"


class DocumentRef(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Kind1
    """
    PDF 종류.
    """
    url: str | None = None
    """
    백엔드 서명 다운로드 URL(단기 만료).
    """


class ReportMeta(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    comm_unique_no: str | None = None
    """
    전유부 고유번호.
    """
    res_doc_no: str | None = None
    """
    전유부 문서확인번호.
    """
    issue_date: str | None = None
    """
    발급일자.
    """
    issue_org: str | None = None
    """
    발급기관.
    """
    queried_at: str | None = None
    """
    조회(스크래핑) 시각.
    """


class NeedsInput(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    kind: Kind
    """
    폴백 종류. dong_ho=주소·동·호 후보 선택 필요, secure_no=보안문자 입력 필요.
    """
    message: str
    """
    사용자 안내용 메시지.
    """
    field: FieldModel | None = None
    """
    kind=dong_ho 일 때 사용자가 골라야 하는 축(address=주소, dong=동, ho=호). options 와 함께 채워진다.
    """
    options: list[NeedsInputOption] | None = None
    """
    선택 후보 목록(CODEF reqAddrList/reqDongNumList/reqHoNumList 정규화). 사용자가 하나를 골라 재개한다. CODEF 자동매칭이 0건/복수건일 때만 채워진다.
    """


class HomeCheckReport(BaseModel):
    """
    전유부+표제부 병행 조회 결과의 PII-free 리포트.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    signal: Signal1
    """
    종합 신호등.
    """
    violation: Violation
    address: AddressInfo
    exclusive_part: ExclusivePart | None = None
    """
    전유부분 요약 (전유부 resOwnedList 중 resType='0').
    """
    building: BuildingHeading | None = None
    """
    건물(표제부) 요약.
    """
    change_history: list[ChangeEntry] | None = None
    """
    전유부+표제부 변동사항(resChangeList) 통합 타임라인. 확장 등재 여부 대조의 핵심.
    """
    extension_check: ExtensionCheck | None = None
    """
    사용자가 신고한 확장·개조 부위와 대장 변동사항을 대조한 LLM 판정. 사용자 입력이 있을 때만 채워진다. 노란딱지(violation)와 별개 축.
    """
    documents: list[DocumentRef] | None = None
    """
    발급 PDF 다운로드 링크(전유부/표제부).
    """
    caution_reasons: list[str] | None = None
    """
    🟡 caution 판정 사유(예: '신고하신 확장이 대장 변동이력에 없음', '전유부 기준이라 건물 위반표시는 별도 확인 필요').
    """
    meta: ReportMeta | None = None
    """
    발급 메타데이터.
    """
    disclaimer: str
    """
    면책 고지(참고용·최종판단은 관할 행정청/전문가).
    """


class HomeCheckJob(BaseModel):
    """
    우리집 체크 조회 잡 + 결과 리포트. CODEF 세움터 집합건축물대장 전유부+표제부 응답을 PII-free 로 매핑한 정본. 결정: docs/adr/0008-home-check-building-register.md. 소유자/설계자 성명·주민번호·세움터 password 등 PII 는 절대 포함하지 않는다(원본 PDF 는 Storage 보관).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["1.3.0"] = Field(..., pattern="^\\d+\\.\\d+\\.\\d+$")
    """
    스키마 버전 (semver). 1.3.0: phase(진행 단계, 정보성 open string) 추가 — 대기 화면 실시간 스텝 표시용. 1.2.0: report 에 extension_check(신고확장↔변동사항 LLM 대조) 추가 + prices(공동주택가격) 제거 — 우리집 체크는 확장 등재 여부가 목적이라 가격/속성 노이즈 제외.
    """
    id: str
    """
    조회 잡 UUID.
    """
    status: Status
    """
    잡 상태. needs_input = 동·호 자동매칭 실패 또는 보안문자(reqSecureNo) 발생 폴백.
    """
    phase: str | None = None
    """
    백그라운드 파이프라인 진행 단계(정보성 — status 가 상태 기계 정본). 알려진 값: received → issuing_registers → judging → saving_report. status=pending|querying 일 때만 의미가 있으며 터미널 상태에선 마지막 값이 남는다. 워커 통합/세분화로 값이 추가될 수 있으므로 엄격 enum 이 아니다 — 클라이언트는 미지의 값을 일반 대기 문구로 폴백해야 한다.
    """
    signal: Signal | None = None
    """
    종합 신호등. status=completed 일 때만 채워진다. violation=🔴, caution=🟡, normal=🟢.
    """
    created_at: str | None = None
    """
    잡 생성 시각 (ISO-8601).
    """
    updated_at: str | None = None
    """
    잡 갱신 시각 (ISO-8601).
    """
    error: ErrorInfo | None = None
    """
    실패 사유 (status=failed).
    """
    needs_input: NeedsInput | None = None
    """
    추가 입력 요구 (status=needs_input).
    """
    report: HomeCheckReport | None = None
    """
    결과 리포트 (status=completed).
    """
