-- CMP-575 Supabase SQL candidate for Alembic revision 0002_deployment_probe_temp.
-- Historical deployment-probe table used by CMP-539.

create table public.deployment_probe_temp (
  id integer generated by default as identity,
  created_at timestamp with time zone not null default now(),
  marker varchar(64) not null default 'cmp-539',
  primary key (id)
);
