-- CMP-575 Supabase SQL candidate for Alembic revision 0005_auth_skeleton.
-- Do not alter Supabase auth.users; Jippin's OAuth-only users live in public.users.

create type public.external_sso_provider as enum (
  'kakao',
  'naver',
  'google'
);

create table public.users (
  id uuid not null default gen_random_uuid(),
  email text,
  display_name text,
  profile_image_url text,
  status text not null default 'active',
  role text not null default 'user',
  last_login_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint pk_users primary key (id),
  constraint ck_users_users_status_allowed check (
    status in ('active', 'suspended', 'deleted')
  )
);

create table public.external_sso_accounts (
  id bigint generated by default as identity,
  user_id uuid not null,
  provider public.external_sso_provider not null,
  provider_subject text not null,
  provider_email text,
  linked_at timestamp with time zone not null default now(),
  display_name text,
  profile_image_url text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint pk_external_sso_accounts primary key (id),
  constraint fk_external_sso_accounts_user_id_users
    foreign key (user_id)
    references public.users (id)
    on delete cascade,
  constraint uq_external_sso_accounts_provider_provider_subject
    unique (provider, provider_subject),
  constraint uq_external_sso_accounts_user_id_provider
    unique (user_id, provider)
);

create table public.anonymous_users (
  id uuid not null default gen_random_uuid(),
  converted_user_id uuid,
  ip_hash bytea,
  ua_hash bytea,
  last_seen_at timestamp with time zone not null default now(),
  converted_at timestamp with time zone,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint pk_anonymous_users primary key (id),
  constraint fk_anonymous_users_converted_user_id_users
    foreign key (converted_user_id)
    references public.users (id)
    on delete set null
);

create index ix_anonymous_users_last_seen_at
  on public.anonymous_users (last_seen_at);

create table public.terms_consents (
  id uuid not null default gen_random_uuid(),
  user_id uuid not null,
  term_id text not null,
  version text not null,
  source text not null,
  agreed_at timestamp with time zone not null default now(),
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint pk_terms_consents primary key (id),
  constraint ck_terms_consents_terms_consents_source_allowed check (
    source in ('kakao_sync', 'internal_signup')
  ),
  constraint fk_terms_consents_user_id_users
    foreign key (user_id)
    references public.users (id)
    on delete cascade,
  constraint uq_terms_consents_user_id_term_id_version_source
    unique (user_id, term_id, version, source)
);
